// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusGameEngine.Infrastructure.Persistance;

#nullable disable

namespace NexusGameEngine.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260925095235_MapZoneMig")]
    partial class MapZoneMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexusGameEngine.Domain.Entities.InventorySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("StatePayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PlayerId");

                    b.ToTable("InventorySlots", (string)null);
                });

            modelBuilder.Entity("NexusGameEngine.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxStackQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ItemsCatalog", (string)null);
                });

            modelBuilder.Entity("NexusGameEngine.Domain.Entities.MapZone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("MapZones", (string)null);
                });

            modelBuilder.Entity("NexusGameEngine.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("BaseMovementSpeed")
                        .HasColumnType("real");

                    b.Property<bool>("IsAlive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("LastMove")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("MapZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Money")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ActiveSpecialSkill", "NexusGameEngine.Domain.Entities.Player.ActiveSpecialSkill#SpecialSkill", b1 =>
                        {
                            b1.Property<double>("BonusPercentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("float(5)")
                                .HasColumnName("SpecialSkill_BonusPercentage");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("SpecialSkill_Name");

                            b1.Property<int>("TargetStat")
                                .HasColumnType("int")
                                .HasColumnName("SpecialSkill_TargetStat");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Constitution", "NexusGameEngine.Domain.Entities.Player.Constitution#Stat", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Experience")
                                .HasColumnType("int");

                            b1.Property<byte>("Level")
                                .HasColumnType("tinyint");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");
                        });

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Cooldowns", "NexusGameEngine.Domain.Entities.Player.Cooldowns#PlayerCooldown", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ActionId")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("ReadyAt");

                            b1
                                .ToJson("Cooldowns")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Dexterity", "NexusGameEngine.Domain.Entities.Player.Dexterity#Stat", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Experience")
                                .HasColumnType("int");

                            b1.Property<byte>("Level")
                                .HasColumnType("tinyint");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Intelligence", "NexusGameEngine.Domain.Entities.Player.Intelligence#Stat", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Experience")
                                .HasColumnType("int");

                            b1.Property<byte>("Level")
                                .HasColumnType("tinyint");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "MainLevel", "NexusGameEngine.Domain.Entities.Player.MainLevel#Stat", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Experience")
                                .HasColumnType("int");

                            b1.Property<byte>("Level")
                                .HasColumnType("tinyint");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PlayerHealth", "NexusGameEngine.Domain.Entities.Player.PlayerHealth#Health", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<short>("CurrentHealth")
                                .HasColumnType("smallint")
                                .HasColumnName("Health");

                            b1.Property<short>("MaxHealth")
                                .HasColumnType("smallint")
                                .HasColumnName("MaxHealth");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PlayerStamina", "NexusGameEngine.Domain.Entities.Player.PlayerStamina#Stamina", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<short>("CurrentStamina")
                                .HasColumnType("smallint")
                                .HasColumnName("Stamina");

                            b1.Property<DateTimeOffset>("LastUpdateTime")
                                .HasColumnType("datetimeoffset");

                            b1.Property<short>("MaxStamina")
                                .HasColumnType("smallint")
                                .HasColumnName("MaxStamina");

                            b1.Property<short>("RegenRatePerSecond")
                                .HasColumnType("smallint")
                                .HasColumnName("StaminaRegenRate");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Strength", "NexusGameEngine.Domain.Entities.Player.Strength#Stat", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Experience")
                                .HasColumnType("int");

                            b1.Property<byte>("Level")
                                .HasColumnType("tinyint");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "WorldPosition", "NexusGameEngine.Domain.Entities.Player.WorldPosition#Vector3", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<float>("X")
                                .HasColumnType("real")
                                .HasColumnName("Pos_X");

                            b1.Property<float>("Y")
                                .HasColumnType("real")
                                .HasColumnName("Pos_Y");

                            b1.Property<float>("Z")
                                .HasColumnType("real")
                                .HasColumnName("Pos_Z");
                        });

                    b.HasKey("Id");

                    b.HasIndex("MapZoneId");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("NexusGameEngine.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Expiry")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("RevokeAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("NexusGameEngine.Domain.Entities.SystemRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AdminRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SystemRoles", (string)null);
                });

            modelBuilder.Entity("NexusGameEngine.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("Email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("SystemRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SystemRoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("NexusGameEngine.Domain.Entities.InventorySlot", b =>
                {
                    b.HasOne("NexusGameEngine.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusGameEngine.Domain.Entities.Player", "Player")
                        .WithMany("InventorySlots")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NexusGameEngine.Domain.Entities.Player", b =>
                {
                    b.HasOne("NexusGameEngine.Domain.Entities.User", "User")
                        .WithOne("Player")
                        .HasForeignKey("NexusGameEngine.Domain.Entities.Player", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusGameEngine.Domain.Entities.MapZone", "MapZone")
                        .WithMany()
                        .HasForeignKey("MapZoneId");

                    b.Navigation("MapZone");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexusGameEngine.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("NexusGameEngine.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexusGameEngine.Domain.Entities.User", b =>
                {
                    b.HasOne("NexusGameEngine.Domain.Entities.SystemRole", "SystemRole")
                        .WithMany()
                        .HasForeignKey("SystemRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SystemRole");
                });

            modelBuilder.Entity("NexusGameEngine.Domain.Entities.Player", b =>
                {
                    b.Navigation("InventorySlots");
                });

            modelBuilder.Entity("NexusGameEngine.Domain.Entities.User", b =>
                {
                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
